#!/bin/bash

python main.py \
    --mode train \
    --exper-name m2max_safe_end_to_end \
    --gpu 0 \
    --epochs 50 \
    --batch-size 8 \
    --lr 1e-5 \
    --lr-image-encoder 0.0 \
    --lr-prompt-learner 1e-5 \
    --lr-adapter 1e-5 \
    --weight-decay 0.0001 \
    --momentum 0.9 \
    --milestones 20 35 \
    --gamma 0.1 \
    --temporal-layers 1 \
    --num-segments 16 \
    --duration 1 \
    --image-size 224 \
    --seed 42 \
    --print-freq 10 \
    --root-dir /kaggle/input/raer-video-emotion-dataset \
    --train-annotation /kaggle/input/raer-annot/annotation/train.txt \
    --val-annotation /kaggle/input/raer-annot/annotation/test.txt \
    --test-annotation /kaggle/input/raer-annot/annotation/test.txt \
    --clip-path ViT-B/32 \
    --bounding-box-face /kaggle/input/raer-video-emotion-dataset/RAER/bounding_box/face.json \
    --bounding-box-body /kaggle/input/raer-video-emotion-dataset/RAER/bounding_box/body.json \
    --text-type class_descriptor \
    --contexts-number 12 \
    --class-token-position end \
    --class-specific-contexts True \
    --load_and_tune_prompt_learner True \
    --lambda_mi 0.7 \
    --lambda_dc 1.2 \
    --mi-warmup 5 \
    --mi-ramp 8 \
    --dc-warmup 5 \
    --dc-ramp 10 \
    --slerp-weight 0.5 \
    --logit-adj \
    --logit-adj-tau 0.5 \
    --temperature 0.07 \
    --use-weighted-sampler \
    --label-smoothing 0.05 \
    --use-amp \
    --crop-body \
    --grad-clip 1.0